"""
Fine-tune Whisper on one or more Common Voice-style datasets, e.g.:
  - common_voice        official Bashkir Common Voice (download_common_voice_mdc.py),
                         has proper train.tsv/dev.tsv splits
  - common_voice_elang   generated by eaf_to_common_voice.py, train.tsv only
  - common_voice_pairs   generated by pairs_to_common_voice.py, train.tsv only

For a directory that has an eval split file (--eval-tsv, default dev.tsv), that
split is used as-is. For a directory without one, a small held-out slice is
carved out of its train.tsv (--eval-fraction, seeded by --eval-seed) so every
source still contributes eval signal. All directories' train/eval portions are
concatenated into one combined DatasetDict before training.

If a directory also has --test-tsv (default test.tsv - only the official
common_voice download has one), that split is kept separate: never used for
training or for periodic eval/checkpoint selection, only scored once after
training finishes, as a clean, unleaked final held-out metric.

Feature extraction (audio -> log-mel input_features) is done in small,
independently disk-cached chunks (--precompute-chunk-size) under
<output-dir>/feature_cache/, rather than one giant dataset.map() call: with
~175k examples spanning an hours-long real-world mp3 dump, a single corrupt
file or transient OOM can kill a worker with an uncatchable native crash
partway through - losing all progress if done as one big map(). Chunking
means a crash only costs one chunk (a couple of minutes), already-finished
chunks are skipped on retry, and a chunk that keeps crashing is automatically
bisected to isolate and skip the single offending example rather than
blocking the whole run.

After training, the model is evaluated on each data directory's held-out test.tsv
(if present) via evaluate_test_sets.py - full WER/CER/MER/WIL + empty-hypothesis-rate
scoring (not the raw, unnormalized token-level WER Seq2SeqTrainer.evaluate() would
otherwise give), with per-sample results written to
<output-dir>/<data-dir-name>_test_asr_eval.csv. Run evaluate_test_sets.py directly to
re-score a saved checkpoint later without retraining.

Requires:
  pip install transformers datasets evaluate jiwer accelerate librosa soundfile torchaudio tqdm matplotlib
  ffmpeg installed and on PATH (needed to decode the .mp3 clips)

Usage:
  python whisper.py --data-dirs common_voice common_voice_elang common_voice_pairs \
      --model openai/whisper-medium --output-dir whisper-ba
"""

import argparse
import json
from dataclasses import dataclass
from multiprocessing import Pool
from pathlib import Path
from typing import Any

import pandas as pd

LANGUAGE = "Bashkir"
TASK = "transcribe"
# Hardcoded across all Whisper checkpoint sizes (WhisperConfig.max_target_positions);
# the decoder can never produce or accept a label sequence longer than this.
MAX_LABEL_LENGTH = 448


def _is_readable_audio(path: str) -> bool:
    import soundfile as sf

    try:
        return sf.info(path).frames > 0
    except Exception:
        return False


def _load_readable_cache(cache_path: Path) -> dict[str, bool]:
    if cache_path.exists():
        try:
            return json.loads(cache_path.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}


def _save_readable_cache(cache_path: Path, cache: dict[str, bool]) -> None:
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_text(json.dumps(cache), encoding="utf-8")


def filter_unreadable_audio(df: pd.DataFrame, num_proc: int, cache_path: Path | None = None) -> pd.DataFrame:
    """Drop rows whose audio file can't be opened, so a single corrupt clip
    (common in large scraped mp3 dumps) can't kill an hours-long map() worker
    with an uncatchable native-library crash partway through preprocessing.

    Results are cached to disk keyed by audio path, so re-running the script
    (e.g. after a crash) only checks files that weren't checked before,
    instead of re-scanning all ~175k clips with soundfile every time."""
    cache = _load_readable_cache(cache_path) if cache_path else {}
    paths = df["audio"].tolist()
    to_check = [p for p in paths if p not in cache]
    if to_check:
        with Pool(num_proc) as pool:
            results = pool.map(_is_readable_audio, to_check, chunksize=64)
        cache.update(zip(to_check, results))
        if cache_path:
            _save_readable_cache(cache_path, cache)
    valid = pd.Series([cache[p] for p in paths], index=df.index)
    n_bad = (~valid).sum()
    if n_bad:
        examples = df.loc[~valid, "audio"].head(5).tolist()
        print(f"    dropping {n_bad} unreadable/corrupt clip(s), e.g.: {examples}")
    return df[valid].reset_index(drop=True)


def load_split(data_dir: Path, tsv_name: str, num_proc: int) -> pd.DataFrame:
    tsv_path = data_dir / tsv_name
    if not tsv_path.exists():
        raise SystemExit(f"Expected split file not found: {tsv_path}")

    df = pd.read_csv(tsv_path, sep="\t", usecols=["path", "sentence"])
    clips_dir = data_dir / "clips"
    df["audio"] = df["path"].apply(lambda p: str(clips_dir / p))
    cache_path = data_dir / f".{tsv_name}.readable_cache.json"
    df = filter_unreadable_audio(df[["audio", "sentence"]], num_proc, cache_path)
    return df


def build_dataset(
    data_dirs: list[Path], train_tsv: str, eval_tsv: str, test_tsv: str,
    eval_fraction: float, eval_seed: int, num_proc: int,
):
    from datasets import Audio, Dataset, DatasetDict, concatenate_datasets

    train_parts, eval_parts, test_parts = [], [], []
    for data_dir in data_dirs:
        train_df = load_split(data_dir, train_tsv, num_proc)
        eval_path = data_dir / eval_tsv
        if eval_path.exists():
            train_ds = Dataset.from_pandas(train_df, preserve_index=False)
            eval_ds = Dataset.from_pandas(load_split(data_dir, eval_tsv, num_proc), preserve_index=False)
        else:
            print(f"  {data_dir}: no {eval_tsv}, carving out {eval_fraction:.1%} of train.tsv for eval")
            split = Dataset.from_pandas(train_df, preserve_index=False).train_test_split(
                test_size=eval_fraction, seed=eval_seed
            )
            train_ds, eval_ds = split["train"], split["test"]

        test_path = data_dir / test_tsv
        test_note = ""
        if test_path.exists():
            test_ds = Dataset.from_pandas(load_split(data_dir, test_tsv, num_proc), preserve_index=False)
            test_parts.append(test_ds)
            test_note = f", {len(test_ds)} held-out test"

        print(f"  {data_dir}: {len(train_ds)} train, {len(eval_ds)} eval{test_note}")
        train_parts.append(train_ds)
        eval_parts.append(eval_ds)

    dataset = DatasetDict({
        "train": concatenate_datasets(train_parts).shuffle(seed=eval_seed),
        "eval": concatenate_datasets(eval_parts),
    })
    if test_parts:
        dataset["test"] = concatenate_datasets(test_parts)
    return dataset.cast_column("audio", Audio(sampling_rate=16000))


def safe_map_chunk(chunk, prepare_example, remove_columns: list[str], num_proc: int, depth: int = 0):
    """map() a chunk, bisecting and retrying on an abrupt worker death instead
    of propagating it. Isolates a single poison example (that crashes even
    alone) by skipping it with a warning (returns None) rather than losing
    the whole run - a 0-row map() can't infer the right output schema, so
    the skip is represented as None and filtered out by the caller instead."""
    from datasets import Audio, concatenate_datasets

    n = len(chunk)
    proc = 1 if n <= 8 else min(num_proc, max(1, n // 4))
    try:
        return chunk.map(
            prepare_example, remove_columns=remove_columns, num_proc=proc, writer_batch_size=200
        )
    except RuntimeError as e:
        if "abruptly died" not in str(e):
            raise
        if n == 1:
            try:
                raw_path = chunk.cast_column("audio", Audio(decode=False))[0]["audio"]["path"]
            except Exception:
                raw_path = "<path unavailable>"
            print(f"    poison example skipped (crashes a worker even alone): {raw_path}")
            return None
        mid = n // 2
        print(f"    chunk of {n} crashed (depth {depth}), bisecting and retrying ...")
        left = safe_map_chunk(chunk.select(range(0, mid)), prepare_example, remove_columns, num_proc, depth + 1)
        right = safe_map_chunk(chunk.select(range(mid, n)), prepare_example, remove_columns, num_proc, depth + 1)
        parts = [p for p in (left, right) if p is not None]
        return concatenate_datasets(parts) if parts else None


def precompute_split(
    name: str, ds, prepare_example, remove_columns: list[str],
    cache_root: Path, chunk_size: int, num_proc: int,
):
    from datasets import concatenate_datasets, load_from_disk

    n = len(ds)
    n_chunks = max(1, (n + chunk_size - 1) // chunk_size)
    chunk_datasets = []
    for i in range(n_chunks):
        start, end = i * chunk_size, min((i + 1) * chunk_size, n)
        chunk_dir = cache_root / name / f"chunk_{i:06d}"
        if (chunk_dir / "dataset_info.json").exists():
            chunk_datasets.append(load_from_disk(str(chunk_dir)))
            continue
        print(f"  [{name}] chunk {i + 1}/{n_chunks} ({start}:{end}) ...")
        processed = safe_map_chunk(ds.select(range(start, end)), prepare_example, remove_columns, num_proc)
        if processed is None:
            print(f"  [{name}] chunk {i + 1}/{n_chunks}: entirely poison, skipping (not cached, will retry next run)")
            continue
        processed.save_to_disk(str(chunk_dir))
        chunk_datasets.append(processed)
    return concatenate_datasets(chunk_datasets)


def plot_training_curve(log_history: list[dict], output_dir: Path) -> None:
    """Plot train/eval loss (and eval WER, if computed) over training steps
    from the trainer's log_history and save it as training_curve.png under
    output_dir."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    train_steps = [e["step"] for e in log_history if "loss" in e]
    train_loss = [e["loss"] for e in log_history if "loss" in e]
    eval_steps = [e["step"] for e in log_history if "eval_loss" in e]
    eval_loss = [e["eval_loss"] for e in log_history if "eval_loss" in e]
    eval_wer = [e["eval_wer"] for e in log_history if "eval_wer" in e]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))

    ax1.plot(train_steps, train_loss, label="train loss", color="tab:blue")
    if eval_steps:
        ax1.plot(eval_steps, eval_loss, label="eval loss", color="tab:orange", marker="o")
    ax1.set_xlabel("step")
    ax1.set_ylabel("loss")
    ax1.set_title("Loss")
    ax1.legend()
    ax1.grid(alpha=0.3)

    if eval_wer:
        ax2.plot(eval_steps, eval_wer, label="eval WER", color="tab:green", marker="o")
        ax2.set_xlabel("step")
        ax2.set_ylabel("WER (%)")
        ax2.set_title("Eval WER")
        ax2.legend()
        ax2.grid(alpha=0.3)
    else:
        ax2.axis("off")

    fig.tight_layout()
    out_path = Path(output_dir) / "training_curve.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Training curve saved to {out_path}")


@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any

    def __call__(self, features: list[dict]) -> dict:
        import torch

        input_features = [{"input_features": f["input_features"]} for f in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")
        labels = labels_batch["input_ids"].masked_fill(labels_batch["attention_mask"].ne(1), -100)
        if (labels[:, 0] == self.processor.tokenizer.bos_token_id).all().cpu().item():
            labels = labels[:, 1:]
        batch["labels"] = labels
        return batch


def main():
    parser = argparse.ArgumentParser(description="Fine-tune Whisper on one or more Common Voice-style datasets")
    parser.add_argument(
        "--data-dirs", nargs="+",
        default=["common_voice", "common_voice_elang", "common_voice_pairs"],
        help="One or more dataset directories to combine for training",
    )
    parser.add_argument("--train-tsv", default="train.tsv")
    parser.add_argument("--eval-tsv", default="dev.tsv", help="Used when present; otherwise carved from train.tsv")
    parser.add_argument(
        "--test-tsv", default="test.tsv",
        help="Used when present, kept separate from training/eval and scored once after training",
    )
    parser.add_argument("--eval-fraction", type=float, default=0.02, help="Held-out fraction for dirs without --eval-tsv")
    parser.add_argument("--eval-seed", type=int, default=42)
    parser.add_argument("--model", default="openai/whisper-medium", help="Base checkpoint to fine-tune")
    parser.add_argument("--output-dir", default="whisper-ba")
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--eval-batch-size", type=int, default=1)
    parser.add_argument("--grad-accum", type=int, default=1)
    parser.add_argument("--learning-rate", type=float, default=1e-5)
    parser.add_argument("--max-steps", type=int, default=10000)
    parser.add_argument("--warmup-steps", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--eval-steps", type=int, default=500)
    parser.add_argument("--save-steps", type=int, default=500)
    parser.add_argument("--num-proc", type=int, default=8, help="Parallel workers for audio preprocessing")
    parser.add_argument("--dataloader-num-workers", type=int, default=8)
    parser.add_argument(
        "--precompute-chunk-size", type=int, default=2000,
        help="Feature extraction is disk-cached in chunks this size, so a crash only costs one chunk",
    )
    args = parser.parse_args()

    import evaluate
    from transformers import (
        Seq2SeqTrainer,
        Seq2SeqTrainingArguments,
        WhisperForConditionalGeneration,
        WhisperProcessor,
    )

    data_dirs = [Path(d) for d in args.data_dirs]
    print("Loading datasets:")
    dataset = build_dataset(
        data_dirs, args.train_tsv, args.eval_tsv, args.test_tsv, args.eval_fraction, args.eval_seed,
        args.num_proc,
    )
    test_note = f", {len(dataset['test'])} held-out test" if "test" in dataset else ""
    print(f"Combined: {len(dataset['train'])} train examples, {len(dataset['eval'])} eval examples{test_note}")

    processor = WhisperProcessor.from_pretrained(args.model, language=LANGUAGE, task=TASK)

    def prepare_example(batch):
        audio = batch["audio"]
        batch["input_features"] = processor.feature_extractor(
            audio["array"], sampling_rate=audio["sampling_rate"]
        ).input_features[0]
        batch["labels"] = processor.tokenizer(batch["sentence"]).input_ids
        return batch

    remove_columns = dataset["train"].column_names
    cache_root = Path(args.output_dir) / "feature_cache"
    print(f"Extracting features (cached under {cache_root}) ...")
    from datasets import DatasetDict

    # "test" is intentionally left untokenized: it's never fed to the trainer, only
    # scored after training by re-decoding its raw audio (see the final eval below),
    # so precomputing/caching its log-mel features here would be wasted work.
    dataset = DatasetDict({
        split_name: precompute_split(
            split_name, split, prepare_example, remove_columns,
            cache_root, args.precompute_chunk_size, args.num_proc,
        )
        for split_name, split in dataset.items() if split_name != "test"
    })

    for split_name, split in dataset.items():
        filtered = split.filter(lambda ex: len(ex["labels"]) <= MAX_LABEL_LENGTH, num_proc=args.num_proc)
        n_dropped = len(split) - len(filtered)
        if n_dropped:
            print(f"  [{split_name}] dropping {n_dropped} example(s) with labels longer than {MAX_LABEL_LENGTH} tokens")
        dataset[split_name] = filtered

    data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)
    wer_metric = evaluate.load("wer")

    def compute_metrics(pred):
        pred_ids = pred.predictions
        label_ids = pred.label_ids
        label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

        pred_str = processor.tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
        label_str = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

        wer = 100 * wer_metric.compute(predictions=pred_str, references=label_str)
        return {"wer": wer}

    model = WhisperForConditionalGeneration.from_pretrained(args.model)
    model.generation_config.language = LANGUAGE
    model.generation_config.task = TASK
    model.generation_config.forced_decoder_ids = None

    training_args = Seq2SeqTrainingArguments(
        output_dir=args.output_dir,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.eval_batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.learning_rate,
        warmup_steps=args.warmup_steps,
        max_steps=args.max_steps,
        seed=args.seed,
        gradient_checkpointing=True,
        bf16=True,
        tf32=True,
        optim="adamw_torch_fused",
        dataloader_num_workers=args.dataloader_num_workers,
        eval_strategy="steps",
        eval_steps=args.eval_steps,
        save_steps=args.save_steps,
        save_total_limit=3,
        predict_with_generate=True,
        generation_max_length=225,
        logging_steps=25,
        load_best_model_at_end=True,
        metric_for_best_model="wer",
        greater_is_better=False,
        report_to=["none"],
    )

    from transformers.trainer_utils import get_last_checkpoint

    last_checkpoint = get_last_checkpoint(args.output_dir) if Path(args.output_dir).is_dir() else None
    if last_checkpoint:
        print(f"Found existing checkpoint, resuming training from {last_checkpoint}")

    trainer = Seq2SeqTrainer(
        args=training_args,
        model=model,
        train_dataset=dataset["train"],
        eval_dataset=dataset["eval"],
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        processing_class=processor,
    )

    trainer.train(resume_from_checkpoint=last_checkpoint)
    trainer.save_model(args.output_dir)
    processor.save_pretrained(args.output_dir)
    plot_training_curve(trainer.state.log_history, Path(args.output_dir))
    print(f"Model saved to {args.output_dir}")

    from evaluate_test_sets import evaluate_test_sets

    # fallback_tsv=None: these are the dirs just trained on, so a dir without a true
    # --test-tsv (only common_voice has one) must be skipped, never scored on its own train.tsv.
    evaluate_test_sets(
        args.output_dir, data_dirs, args.test_tsv, Path(args.output_dir),
        batch_size=args.eval_batch_size, num_workers=args.dataloader_num_workers, fallback_tsv=None,
    )


if __name__ == "__main__":
    main()
